### ISSUE TITLE
Energy Level Filter

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/QuantumAnnealingAnalytics.jl#4]
One nice feature that could be helpful in most plots would be to filter the states that are presented by the Ising energy levels.  The default would be to print all states but setting this new parameter to `1` would only display ground states, `2` would be ground states and first excited states.  The `compute_ising_energy_levels` function can support the filtering process.

**Comment by zmorrell** [comment]
@ccoffrin I realized that some of the plotting functions (namely `plot_states` and `plot_states_dwisc`) already have something similar to this through the num_states argument.  This used in conjunction with ordering by energy could be a way to achieve this, though it would require the user to specify the number of states for the energy levels they want on their own.  Does it seem adequate to add energy sorting to `plot_states` and call it good?

In a similar vein, specifically which functions would we want this in?  I don't think there is a straightforward way to add this to `plot_hamiltonian_energy_spectrum` due to crossings and whatnot, but would we want to add this do `plot_state_steps` and `plot_varied_time_simulations` to filter the states down?

**Comment by ccoffrin** [comment]
I agree we can leave it out for `plot_hamiltonian_energy_spectrum` in the near term, but we can add it to a wishlist for improving that feature to track states more explicitly.  I agree we should add it to `plot_state_steps` and `plot_varied_time_simulations` in these types of plots (and also `plot_states`) I think the most common uses cases are: show all, show only ground states, show ground states and first excited states. Using an "energy level" filter seems like a convenient tool to that end.

There are a couple of ways I can imagine engineering it, you can take a first stab at it.  One option is to pass a collection of integers to the plotting functions, which are the subsets of states that should be shown and then provide some helper functions to determine that set, such as the one QA provides for organizing states into energy levels.
